name: Publish to TestPyPI

on:
  release:
    types: [published]  # 仅在创建 GitHub Release 时触发
  workflow_dispatch:

permissions:
  id-token: write  # 这是关键，启用 OIDC
  contents: read  # 添加内容读取权限

jobs:
  pypi-publish:
    name: Upload release to TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # 与你的pyproject.toml中指定的Python版本一致

      - name: Install dependencies
        run: python -m pip install build twine

      - name: Build package
        run: python -m build --sdist --wheel --outdir dist/

      - name: Verify package
        run: twine check dist/*

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true